type User {
  id: ID!
  name: String!
  username: String
  type: String
  email: String
  password: String
  city: String
  country: String
  businessName: String
  businessType: String
  businessDescription: String
  socialMedia: String
  rating: Number
  ratings: Number
  createdAt: Date
  age: Number
  gender: String
  identifyAs: String
  pronouns: String
}
